//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Core.Properties.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ bao gồm số.
        /// </summary>
        internal static string Contain_Numbers_Only {
            get {
                return ResourceManager.GetString("Contain_Numbers_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001.
        /// </summary>
        internal static string Contain_Numbers_Only_ErrorCode {
            get {
                return ResourceManager.GetString("Contain_Numbers_Only_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên {0} đã tồn tại trong hệ thống, vui lòng kiểm tra lại..
        /// </summary>
        internal static string Duplicate_Code {
            get {
                return ResourceManager.GetString("Duplicate_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002.
        /// </summary>
        internal static string Duplicate_Code_ErrorCode {
            get {
                return ResourceManager.GetString("Duplicate_Code_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003.
        /// </summary>
        internal static string EmployeeCodeError_ErrorCode {
            get {
                return ResourceManager.GetString("EmployeeCodeError_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống.
        /// </summary>
        internal static string Empty_EmployeeCode {
            get {
                return ResourceManager.GetString("Empty_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004.
        /// </summary>
        internal static string Empty_EmployeeCode_ErrorCode {
            get {
                return ResourceManager.GetString("Empty_EmployeeCode_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này không được để trống.
        /// </summary>
        internal static string Empty_Field {
            get {
                return ResourceManager.GetString("Empty_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005.
        /// </summary>
        internal static string Empty_Field_ErrorCode {
            get {
                return ResourceManager.GetString("Empty_Field_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        internal static string Error_Email {
            get {
                return ResourceManager.GetString("Error_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006.
        /// </summary>
        internal static string Error_Email_ErrorCode {
            get {
                return ResourceManager.GetString("Error_Email_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Vui lòng liên hệ MISA.
        /// </summary>
        internal static string Error_Message_UserVN {
            get {
                return ResourceManager.GetString("Error_Message_UserVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007.
        /// </summary>
        internal static string Error_Message_UserVN_ErrorCode {
            get {
                return ResourceManager.GetString("Error_Message_UserVN_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        internal static string Error_PhoneNumber {
            get {
                return ResourceManager.GetString("Error_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 008.
        /// </summary>
        internal static string Error_PhoneNumber_ErrorCode {
            get {
                return ResourceManager.GetString("Error_PhoneNumber_ErrorCode", resourceCulture);
            }
        }
    }
}
